### ISSUE TITLE
Could not find io.github.yuweiguocn:scanner:1.0.2.

### ISSUE THREAD

**Issue by yanchunlan** [yuweiguocn/Scanner#2]
Could not find io.github.yuweiguocn:scanner:1.0.2.
Searched in the following locations:
  - file:/Users/yanchunlan/.m2/repository/io/github/yuweiguocn/scanner/1.0.2/scanner-1.0.2.pom
  - file:/Users/yanchunlan/.m2/repository/io/github/yuweiguocn/scanner/1.0.2/scanner-1.0.2.jar
  - https://dl.google.com/dl/android/maven2/io/github/yuweiguocn/scanner/1.0.2/scanner-1.0.2.pom
  - https://dl.google.com/dl/android/maven2/io/github/yuweiguocn/scanner/1.0.2/scanner-1.0.2.jar
  - https://jcenter.bintray.com/io/github/yuweiguocn/scanner/1.0.2/scanner-1.0.2.pom
  - https://jcenter.bintray.com/io/github/yuweiguocn/scanner/1.0.2/scanner-1.0.2.jar
Required by:
    project :

**Comment by yuweiguocn** [comment]
Done.
